Feature/live site
RevolutionUC/revuc-astro-frontend pull request #51
Opened 2024-02-22 01:55 UTC by chaung844

Added live site (excluded for now)
Added redirect to live site if _siteConfigData.timeline === "live"_ (config.json)

2024-02-22 02:10 UTC, menamerai requested changes

2024-02-22 02:10 UTC, menamerai commented on package-lock.json
Remove this file. We use yarn, so `package-lock.json` should not be here.

2024-02-22 02:10 UTC, menamerai commented on src/components/Hero.astro
>  let date = "    February 24-25    ".toUpperCase(); // Keep the space in order to match with the RevolutionUC Text
Can you hide this for the livesite? We don't need the date when the hackathon is live.

2024-02-22 02:10 UTC, menamerai commented on src/pages/_live.astro
Can you add some "quick links" that hackers can refer to on the livesite? It'll be these links:

![image](https://github.com/RevolutionUC/revuc-astro-frontend/assets/62800649/08581043-69a8-42af-82aa-35d27f922413)

2024-02-22 18:28 UTC, menamerai commented
Some pushes were made sine your last update, you might need to rebase or merge

2024-02-23 06:02 UTC, chaung844 commented on src/pages/_live.astro
not sure where to place them 
<img width="1507" alt="Screenshot 2024-02-23 at 12 59 21 AM" src="https://github.com/RevolutionUC/revuc-astro-frontend/assets/85209423/8b64d326-fb65-4e6f-b79d-28d4bc55a882">

2024-02-23 19:08 UTC, menamerai approved these changes

2024-02-23 19:08 UTC, merged